version: "3.8"
name: hw09
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  code :
    tty: true
    stdin_open: true
    build: ./
    env_file:
      - ./.env

    depends_on:
      - redis

